version: "3.8"

services:
  node-app:
    image: rexxx9865/jenkinsnodeapp:1.0.1
    container_name: node-calculator
    expose:
      - "3000"
    restart: always

  nginx:
    image: nginx:1.29
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - node-app
    restart: always

